### ISSUE TITLE
Splitted features ignores new line symbol escaping (\\n)

### ISSUE THREAD

**Issue by eugs** [AlexGalichenko/cucumber-e2e-gherkin-parallel#6]
Hello
I've noticed that in case we have escaped \n symbols in scenario outlines there's missed backslash character after feature compilation and it leads to failed assertions

e.g.

Feature file **before** compilation:
```
Examples:
| regex     |
| 111\\n111 |
```

Feature file **after** compilation:
```
Examples:
| regex     |
| 111\n111  |

```

**Comment by AlexGalichenko** [comment]
PR https://github.com/AlexGalichenko/cucumber-e2e-gherkin-parallel/pull/7

**Comment by AlexGalichenko** [comment]
https://github.com/AlexGalichenko/cucumber-e2e-gherkin-parallel/pull/8

**Comment by AlexGalichenko** [comment]
hope we are happy now :)
